### ISSUE TITLE
加密算法错误

### ISSUE THREAD

**Issue by AliasQli** [black-binary/hust-network-login#3]
我使用这个认证工具显示密码错误。经过与网页端的请求比对，我发现认证工具加密出的密码是
```
ffeb8... (length 255)
```
网页端的密码是
```
0ffeb8... (length 256)
```
我怀疑网页端的加密算法会对长度不到256的结果填上先导0，不过没有进一步验证。

**Comment by black-binary** [comment]
@EarthCompass 队友救一下

**Comment by EarthCompass** [comment]
修了（大概）（这个repo的issue我收不到提醒啊）

**Comment by EarthCompass** [comment]
> 修了（大概）（这个repo的issue我收不到提醒啊）

得watch一下了
