### ISSUE TITLE
mt7621用哪一个，mipsel好像用不了

### ISSUE THREAD

**Issue by JarmoHu** [black-binary/hust-network-login#5]
opkg update && opkg install unzip
echo -e "D202212345\nABC12345" > /tmp/hust.conf
wget -O /tmp/hust.zip https://gh.con.sh/https://github.com/black-binary/hust-network-login/releases/download/v0.1.3/mipsel-unknown-linux-musl.zip
cd /tmp  && unzip /tmp/hust.zip
chmod +x ./hust-network-login
./hust-network-login ./hust.conf

[JDC-1 /tmp]# /tmp/hust-network-login /tmp/hust.conf
-sh: /tmp/hust-network-login: not found

**Comment by JarmoHu** [comment]
补充一下，我用的硬件平台是京东云无线宝一代-AC2100。CPU是MT7621，固件是hiboy的最新2023-12-1固件（下载地址：[JDC](https://opt.cn2qq.com/padavan/JDC-1_3.4.3.9-099.trx)）

**Comment by JarmoHu** [comment]
是不是需要编译的时候设置软件浮点？
https://harrychen.xyz/2023/09/03/cross-compile-rust-to-mipsel/

**Comment by EarthCompass** [comment]
> 补充一下，我用的硬件平台是京东云无线宝一代-AC2100。CPU是MT7921，固件是hiboy的最新2023-12-1固件（下载地址：[JDC](https://opt.cn2qq.com/padavan/JDC-1_3.4.3.9-099.trx)）

根据[这里](https://www.acwifi.net/15132.html)的数据，京东云无线宝一代-AC2100是MT7621，应该是typo？

手上可能刚好有个MT7621，我去看看。

**Comment by JarmoHu** [comment]
> > 补充一下，我用的硬件平台是京东云无线宝一代-AC2100。CPU是MT7921，固件是hiboy的最新2023-12-1固件（下载地址：[JDC](https://opt.cn2qq.com/padavan/JDC-1_3.4.3.9-099.trx)）
> 
> 根据[这里](https://www.acwifi.net/15132.html)的数据，京东云无线宝一代-AC2100是MT7621，应该是typo？
> 
> 手上可能刚好有个MT7621，我去看看。

啊啊，不好意思，我记错了。确实是MT7621

**Comment by EarthCompass** [comment]
修了一下，试试这个能不能用？
https://github.com/EarthCompass/hust-network-login/releases/download/v0.1.4-beta/mipsel-unknown-linux-musl.zip

**Comment by JarmoHu** [comment]
问题解决了，非常感谢。
请教如何入门学习rust
